name: Scala/Java Code Linting Check
on: [push]
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Check scalafmt
        run: sbt scalafmtCheckAll
  scalastyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Check scalastyle
        run: sbt "scalastyle; Test/scalastyle"
  javafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Check javafmt
        run: sbt javafmtCheckAll
