name: Publish Local CI
on: [push]
jobs:
  publishLocal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 21 ]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Publish Local
        run: sbt "+publishLocal"